# Redis database index(default is 0)
#spring.redis.database=0

# Redis server address
#spring.redis.host=127.0.0.1

# Redis server port
#spring.redis.port=6379

#spring.redis.timeout=3000

#spring.redis.lettuce.pool.max-active=6
#spring.redis.lettuce.pool.max-wait=5
#spring.redis.lettuce.pool.min-idle=1


spring:
  redis:
    myconfig:
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-total: 600
          max-active: 500
          min-active: 60
          max-wait: 50
          max-idle: 150
          min-idle: 100